# Compile pipeline

trigger:
- master
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Start maven compile process for $(pom)!
  displayName: 'Compile $(pom)'
- task: Maven@3
  inputs:
    mavenPomFile: '$(pom)'
    goals: 'clean install'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false