# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
  vmImage: 'ubuntu-1604'



steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: mvn compile
  displayName: 'Build'
- script: mvn verify
  displayName: 'Unit testing'
- script: mvn pitest-maven:mutationCoverage
  displayName: 'mutations testing'
- script: mvn package
  displayName: 'End'
