name: FrontEnd Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  react_test:
    runs-on: ubuntu-latest
    name: test front
    steps:
    - uses: actions/checkout@master
      with:
       fetch-depth: 0
    - name: npm set up
      uses: actions/setup-node@v4.0.3
      with:
        node-version: 20
    - name: compile
      run: |
        cd frontend
        npm install
    - name: test
      run: |
        cd frontend
        npm run test
    - name: sonar cloud
      env:
        SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd frontend
        npm install -g sonarqube-scanner
        sonarqube-scanner -Dsonar.token=$SONAR_TOKEN -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.projectKey=dan323_natural-deduction-frontend