name: FrontEnd Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  react_test:
    runs-on: ubuntu-latest
    name: test front
    steps:
    - uses: actions/checkout@master
      with:
       fetch-depth: 0
    - name: npm set up
      uses: actions/setup-node@v4.0.3
      with:
        node-version: 20
    - name: global dependecies
      run: npm install -g sonarqube-scanner
    - name: compile
      run: |
        cd frontend
        npm install
    - name: test
      run: |
        cd frontend
        npm run test
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2.3.0
      env:
        SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io/
      with:
        projectBaseDir: frontend
        args: >
          - Dsonar.organization=$SONAR_ORGANIZATION