name: FrontEnd Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  react_test:
    runs-on: ubuntu-latest
    name: test front
    steps:
    - uses: actions/checkout@v4
      with:
       fetch-depth: 0
    - name: npm set up
      uses: actions/setup-node@v4.0.3
      with:
        node-version: 20
    - name: compile
      run: |
        cd frontend
        npm install
    - name: test
      run: |
        cd frontend
        npm run test
    - name: sonar cloud frontend
      env:
        SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_PROJECT: ${{ secrets.SONAR_PROJECT }}
      run: |
        cd frontend
        mvn -B -f pom.xml package -Dmaven.test.skip=true org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.java.source=21 -Dsonar.java.target=21 -Dsonar.token=$SONAR_TOKEN -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=$SONAR_ORGANIZATION -Dorganization=$SONAR_ORGANIZATION -Dsonar.projectKey=natural-deduction-front -Dsonar.typescript.tsconfigPaths=.