
on:
  push:
    branches:
      - master

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  create_public:
    runs-on: ubuntu-latest
    name: build frontend and publish in backend
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - name: npm set up
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
      - name: install
        run: |
          cd frontend
          npm install
      - name: build
        run: |
          cd frontend
          npm run build
          mkdir ../executable/src/main/resources/public/
          cp -r ./build/* ../executable/src/main/resources/public/
      - name: Setup java
        uses: actions/setup-java@master
        with:
          java-version: 21
          distribution: 'corretto'
      - name: build
        run: mvn -B -f pom.xml clean package -Dmaven.test.skip=true
      - run: mv executable/target/executable-0.1-SNAPSHOT.jar executable/target/executable-${{ env.build-number }}.jar
      - uses: actions/upload-artifact@v4
        with:
          path: executable/target/executable-${{ env.build-number }}.jar
          retention-days: 1