# This workflow will compile and test verify
# when a push or pull request action on master is activated
# or when a push is done in a release

name: Main Workflow

on:
  pull_request:
    types:
      - closed

env:
  build-number: ${GITHUB_RUN_NUMBER}

jobs:
  create_public:
    runs-on: ubuntu-latest
    name: build frontend and publish in backend
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - name: npm set up
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
      - name: install
        run: |
          cd frontend
          npm install
      - name: build
        run: |
          cd frontend
          npm run build
          mkdir ../executable/src/main/resources/public/
          cp -r ./build/* ../executable/src/main/resources/public/
      - name: Setup java
        uses: actions/setup-java@master
        with:
          java-version: 21
          distribution: 'corretto'
      - name: build
        run: mvn -B -f pom.xml clean package -Dmaven.test.skip=true
      - run: mkdir staging && mv executable/target/executable-0.1-SNAPSHOT.jar executable/target/executable-${{ env.build-number }}.jar && cp executable/target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
          retention-days: 1
  clean_pages:
    runs-on: ubuntu-latest
    name: delete pr info on github page
    steps:
      - uses: actions/checkout@master
        with:
          ref: 'gh-pages'
      - name: remove data from pull request
        env:
          PR: ${{ github.event.pull_request.number }}
        run: git rm -r $PR
      - name: commit changes on web
        env:
          PR: ${{ github.event.pull_request.number }}
        run: |
          git config --local user.email "pr-clean[bot]@users.noreply.github.com"
          git config --local user.name "pr-clean[bot]"
          git commit -m "Removed PR-$PR reports"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: 'gh-pages'
          github_token: ${{ secrets.GITHUB_TOKEN }}